# Generated by Django 5.2.2 on 2025-06-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_asset_assigned_to_remove_asset_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
