# Generated by Django 5.2.2 on 2025-06-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_asset_quantity_alter_asset_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
    ]
