# Generated by Django 5.2.2 on 2025-06-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
