# Generated by Django 5.2.3 on 2025-06-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_usermessage_email_usermessage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermessage",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
